version: "3.3"

services:
    app:
        build: .
        command: npm start
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app
    mysql:
        image: mysql
        container_name: container-mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ../db/data:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"

            